### PR TITLE
Makefile improvements

### PR DESCRIPTION
**Pull request by ojeda**

### CODE REVIEW

**Comment by ksquirrel** [comment]
Review of `8665cfd5ab00`:
  - ⚠️ The PR body message looks too short.
  - ✔️ Commit [`ad1a743`](https://github.com/Rust-for-Linux/linux/commit/ad1a7438979b816506ec35bceb407b335c8d2509): Looks fine!
  - ❌ Commit [`8665cfd`](https://github.com/Rust-for-Linux/linux/commit/8665cfd5ab0046c44b104ca0490f8b2542a2a447): Tag `Suggested-by` must be followed by a name and an email.

**Comment by ojeda** [comment]
@bjorn3 Let me know if you prefer that I add an email to your name (for `Suggested-by` tags etc.).

**Comment by bjorn3** [comment]
You can use bjorn3_gh@protonmail.com. That is my public email: https://github.com/rust-lang/team/blob/master/people/bjorn3.toml#L5

**Comment by ojeda** [comment]
Great, thanks!

**Comment by ksquirrel** [comment]
Review of `f8f3aa1ade8b`:
  - ⚠️ The PR body message looks too short.
  - ✔️ Commit [`ad1a743`](https://github.com/Rust-for-Linux/linux/commit/ad1a7438979b816506ec35bceb407b335c8d2509): Looks fine!
  - ✔️ Commit [`0627f1a`](https://github.com/Rust-for-Linux/linux/commit/0627f1a5a36051235877d699d6eb30f1d8715356): Looks fine!
  - ✔️ Commit [`f8f3aa1`](https://github.com/Rust-for-Linux/linux/commit/f8f3aa1ade8b53aaba8b270a06639b01cb319953): Looks fine!

**Review by bjorn3 — APPROVED** [review]

**Pull request merged**
