### PR TITLE
CI: enable `SAMPLE_RUST_RANDOM` in all CI configs

### LINKED ISSUE #242: Enable `SAMPLE_RUST_RANDOM` (as a module) in all CI configs

### PR DESCRIPTION
**Pull request by wusyong**
Fixes #242

### CODE REVIEW

**Comment by ksquirrel** [comment]
Review of `f5403496205d`:
  - ❌ Commit [`f540349`](https://github.com/Rust-for-Linux/linux/commit/f5403496205d3d08eb332cac85fc315bd18047ff): The commit message needs to be at least 3 lines long: title, empty line, signature.

**Comment by ksquirrel** [comment]
Review of `34318ee0f4aa`:
  - ✔️ Commit [`34318ee`](https://github.com/Rust-for-Linux/linux/commit/34318ee0f4aaf83265885e323cea3ff06375e1a9): Looks fine!

**Comment by TheSven73** [comment]
This looks ok to me.

**Comment by ojeda** [comment]
Thanks!

**Pull request merged**
