### PR TITLE
rust: helpers: Clarify comment on size_t = uintptr_t guard

### PR DESCRIPTION
**Pull request by geofft**
Also fix the guard to not fail spriously on ARM. We just need the types
to be ABI-compatible; we don't need C to be willing to implicitly
convert between them.

Signed-off-by: Geoffrey Thomas <geofft@ldpreload.com>

### CODE REVIEW

**Comment by ksquirrel** [comment]
Review of `33c6546953c5`:
  - ✔️ Commit [`33c6546`](https://github.com/Rust-for-Linux/linux/commit/33c6546953c556d95d0ae2e1d34e724d4de16000): Looks fine!

**Comment by geofft** [comment]
Fixes #329.

(Also happy to see this squashed into whatever, it's effectively cleaning up old linux-kernel-module-rust code and making it presentable :) )

**Comment by alex** [comment]
@geofft can you rebase this on a more recent `rust` branch? It looks to be several months out of date, which is (I think) why CI isn't running.

**Comment by ojeda** [comment]
> @geofft can you rebase this on a more recent `rust` branch? It looks to be several months out of date, which is (I think) why CI isn't running.

The reason that the CI is not running is that this is against `rust-next` -- please do not merge!

Given GitHub does not seem to allow to simply disable PR functionality, and only allows to "protect" some branches (which is enforced on pushes too), I will make @ksquirrel warn about it. Give me a moment to test it.

**Comment by ksquirrel** [comment]
Review of `33c6546953c5`:
  - ❌ The PR must target the `rust` branch.
  - ✔️ Commit [`33c6546`](https://github.com/Rust-for-Linux/linux/commit/33c6546953c556d95d0ae2e1d34e724d4de16000): Looks fine!

**Comment by ksquirrel** [comment]
Review of `3c262d5ce907`:
  - ✔️ Commit [`3c262d5`](https://github.com/Rust-for-Linux/linux/commit/3c262d5ce9075ecb8bc8f7bb083e1238ed3494cb): Looks fine!

**Review by TheSven73 — CHANGES_REQUESTED** [review]
(edited) no worries!

**Review by alex — APPROVED** [review]
Will let other folks have a look at this before merging.

**Review by TheSven73 — APPROVED** [review]
I like this a lot! :100: 

I also noticed that `size_t` and `unsigned long` were completely identical on `arm32`, yet gcc didn't think they were compatible. I'd love to further understand the underlying reason for that.

But that definitely shouldn't hold up this PR!

**Comment by geofft** [comment]
See discussion in #329, but tl;dr the two underlying types are `int` vs. `long`, which are both `u32` but don't satisfy `__builtin_types_compatible_p`. Basically I was wrong in my assumption about what `__builtin_types_compatible_p` does and I am hoping this new check is closer to what we want.

**Comment by TheSven73** [comment]
Indeed. I just don't get why two types which are both 32-bit, unsigned, and using the same rules for arithmetic etc would end up as being marked "not compatible" by gcc /  `__builtin_types_compatible_p`.

**Comment by ojeda** [comment]
> Indeed. I just don't get why two types which are both 32-bit, unsigned, and using the same rules for arithmetic etc would end up as being marked "not compatible" by gcc / `__builtin_types_compatible_p`.

It is just what the C standard says in 6.7.2: `int` and `long` are distinct types. So are `char` and `signed char`. But not `int` and `signed int`! :)

**Comment by TheSven73** [comment]
> It is just what the C standard says in 6.7.2: `int` and `long` are distinct types. So are `char` and `signed char`. But not `int` and `signed int`! :)

I'm looking for the "facepalm" emoji but can't find it on GitHub :)

**Pull request merged**
