### PR TITLE
Add default value for the first parameter of `KernelResult`.

### PR DESCRIPTION
**Pull request by wedsonaf**

### CODE REVIEW

**Comment by ojeda** [comment]
Looks better indeed. Any downsides?

**Comment by wedsonaf** [comment]
> Looks better indeed. Any downsides?

I think that one downside is that it's less obvious to someone unfamiliar that the function returns `()` on success.

But I think that the less populated version is less intimidating to unfamiliar readers.

**Review by ojeda — APPROVED** [review]

**Comment by alex** [comment]
I'm ambivalent. If other folks think this is better, LGTM.

**Comment by ojeda** [comment]
I think we won't know what is best until we know how many % of `<()>` cases we will have around the kernel. If it is just e.g. <= ~20% of them, I'd prefer not to have it.

In general, I don't like default parameters, but in this case given it is `()`, I guess it shouldn't give many problems.

**Comment by ojeda** [comment]
Let's put it in knowing we will revisit this when we have more information.

**Comment by ojeda** [comment]
#132

**Pull request merged**
