### PR TITLE
rust:kernel: add Timer abstraction

### PR DESCRIPTION
**Pull request by cqs21**
Hello guys, when I developed my own device mapper target with Rust, I wrapped the `struct timer_list` like this PR did. I hope you would like it, and any feedback is welcomed.

### CODE REVIEW

**Comment by nbdd0121** [comment]
I believe @fbq is already working on a timer abstraction.

**Comment by fbq** [comment]
Thanks @nbdd0121 ;-)

Yes, I have a version of timer wrapper: https://github.com/fbq/linux/commit/083a79c10e7d0214aa03c32a002a6fa1627816a8. It's happy to see people are interested as well.

@cqs21 I see you are using the similar pattern as we wrap `workqueue`, which looks good. However, one of the drawback is that `timer_list` on stack is not supported since `Arc` is coupled with `Timer` API. `timer_list` on stack is an important usage, which shows that Rust can work with introducing extra memory cost.

Also `Timer` should be `#[pin_data]`, since it contains self-references and should be pinned-initialized.

Other than these two major points, I think your changes are decent ;-) (Haven't given a careful look though). My original plan is to send out the patchset (based on `rust-next`) to mailing list once all the dependencies (`LockClassKey`, and `container_of`) are merged. Though I did find some soundness issues in the `FnTimer`, so a few more changes are needed. I will add you Cced when I send it out.

If you want to continue figuring out the best wrapper for `timer_list` on your own (I know I might want it myself ;-)), I can help review, but please do:

* based on the `rust-next` branch.
* decouple `Timer` with `Arc`.
* make `Timer` a `#[pin_data]`.

But chances are I may send mine anyway if there are people relying on the functionality and I think the code is ready. You are welcome to review it ;-)

**Comment by cqs21** [comment]
> Yes, I have a version of timer wrapper: [fbq/linux@083a79c](https://github.com/fbq/linux/commit/083a79c10e7d0214aa03c32a002a6fa1627816a8). 

@fbq Sorry, I didn't notice that. And I did learn a lot from the workqueue wrapper. I'd like to review your patchset, please let me be Cced. Later, I will close this PR, and thanks for your suggestions ;-)

Another question is how would I find out which functionality is working in progress, it will be great helpful to know that.

**Comment by fbq** [comment]
> > Yes, I have a version of timer wrapper: [fbq/linux@083a79c](https://github.com/fbq/linux/commit/083a79c10e7d0214aa03c32a002a6fa1627816a8).
> 
> @fbq Sorry, I didn't notice that. And I did learn a lot from the workqueue wrapper. I'd like to review your patchset, please let me be Cced. Later, I will close this PR, and thanks for your suggestions ;-)
> 
> Another question is how would I find out which functionality is working in progress, it will be great helpful to know that.

I don't know the best answer, but the rust-for-linux [mail list](http://vger.kernel.org/vger-lists.html#rust-for-linux), archieve [here](https://lore.kernel.org/rust-for-linux/) and our zulip: rust-for-linux.zulipchat.com are good starting points.

**Pull request closed without merging**
