### PR TITLE
cleanup modinfo generation in `module!`

### PR DESCRIPTION
**Pull request by nbdd0121**
Some cleanups that do not depend on `syn`, split from #278

### CODE REVIEW

**Comment by ksquirrel** [comment]
Review of `9fe3ffa18564`:
  - ✔️ Commit [`9fe3ffa`](https://github.com/Rust-for-Linux/linux/commit/9fe3ffa18564ffb0bd34658ca13e22886ea492a0): Looks fine!

**Comment by ksquirrel** [comment]
Review of `23b0a162f1b8`:
  - ✔️ Commit [`23b0a16`](https://github.com/Rust-for-Linux/linux/commit/23b0a162f1b87546b5c252585826aad95ef2bc91): Looks fine!

**Comment by nbdd0121** [comment]
Rebased

**Comment by ksquirrel** [comment]
Review of `e0527c126801`:
  - ✔️ Commit [`e0527c1`](https://github.com/Rust-for-Linux/linux/commit/e0527c1268013df9fa3b4ea355f16c08a5706dcd): Looks fine!

**Comment by ojeda** [comment]
Thanks! It does look better.

I think we will want to end up using the C macros (which should avoid `global_asm` too), but let's take this for the drop to the LKML.

**Pull request merged**
