### PR TITLE
rust: move to stable `rustc` release (`1.55.0`)

### PR DESCRIPTION
**Pull request by AltF02**
Signed-off-by: Matthew Bakhtiari <dev@mtbk.me>

### CODE REVIEW

**Review by alex — APPROVED** [review]

**Comment by nbdd0121** [comment]
This changes the CI part only. The doc and alloc part is not changed.

**Comment by AltF02** [comment]
#496 should fix alloc afaik, I'll take a look at the documentation later today 😄

**Comment by nbdd0121** [comment]
You'll need to diff rust 1.55's liballoc with rust-for-linux's liballoc and port changes.

**Comment by AltF02** [comment]
Cheers, please take a look at #498 when you get the time

**Pull request merged**
