### PR TITLE
rust: docs: update bindgen to `0.59.1`

### PR DESCRIPTION
**Pull request by AltF02**
Signed-off-by: Matthew Bakhtiari dev@mtbk.me

### CODE REVIEW

**Comment by AltF02** [comment]
Looks like to update the CI there needs to be some changes in https://github.com/Rust-for-Linux/ci-bin

**Comment by fbq** [comment]
Hi, could you explain why we need to upgrade? `0.56.0` still works for us, right? (Because we still use that in CI)

**Comment by ojeda** [comment]
Yeah, it would be nice to know if there was a particular reason.

In any case, it is also good to check if newer releases still work, and there might be new features that we might want (e.g. "Constants now have docstrings" is one in 0.59.0), so I have uploaded `bindgen-0.59.1` to https://github.com/Rust-for-Linux/ci-bin for testing.

**Comment by AltF02** [comment]
Mostly because I think we should be testing for newer versions. In case something breaks, because I expect most people to just `emerge -a dev-util/bindgen`. Honestly this pr was made fairly quick and didn't have much thought added to it

**Comment by ojeda** [comment]
Do you want to give a go to the CI with the newer `bindgen`?

(On related news: since I was doing this one, I also took the chance to upload QEMU 6.1.0)

**Comment by ojeda** [comment]
i.e. we should not recommend 0.59.1 in the docs if our CI only uses 0.56.0.

Later on, I plan to have some nightlies that will test different versions of software (`rustc` and `bindgen` at least).

**Comment by AltF02** [comment]
Locally bindgen 0.59.1 works, I'm unsure about qemu 6.1.0, fingers crossed that the CI passes

**Comment by ojeda** [comment]
Please update only bindgen here, i.e. do not update QEMU -- that would be an independent PR (PRs should be independent of each other where possible, i.e. on one we can update bindgen, on another we can update QEMU, etc.). That will also avoid the issue you are seeing in the CI.

**Pull request closed without merging**
