### PR TITLE
Add Rust support for RISC-V arch

### PR DESCRIPTION
**Pull request by nbdd0121**

### CODE REVIEW

**Comment by TheSven73** [comment]
Does this run on QEMU? If so, would it make sense to run this in the CI, like the other architectures?

**Comment by nbdd0121** [comment]
> Does this run on QEMU? If so, would it make sense to run this in the CI, like the other architectures?

It runs on QEMU, but you need to supply a firmware (e.g. OpenSBI). I don't think any distro has that supplied yet, so it means in the CI we have to pull and compile another project, which isn't trivial amount of work.

**Comment by ojeda** [comment]
> we have to pull and compile another project, which isn't trivial amount of work.

We are already cross-compiling Busybox on the fly -- does OpenSBI take long to compile? If not, I can take a look at adding it.

**Comment by memoryruins** [comment]
Ubuntu `20.04` (which I think CI uses) packages [OpenSBI 0.6](https://packages.ubuntu.com/focal/opensbi), `20.10` packages 0.8, and `21.04` packages 0.9.
The most recent version of OpenSBI is [0.9](https://github.com/riscv/opensbi/releases/tag/v0.9) if that matters.

**Comment by nbdd0121** [comment]
> Ubuntu `20.04` (which I think CI uses) packages [OpenSBI 0.6](https://packages.ubuntu.com/focal/opensbi), `20.10` packages 0.8, and `21.04` packages 0.9.
> The most recent version of OpenSBI is [0.9](https://github.com/riscv/opensbi/releases/tag/v0.9) if that matters.

Wow, Ubuntu has OpenSBI packaged, I didn't know that. Debian only has OpenSBI in sid, so I assumed Ubuntu wouldn't have it yet. I'll look to see if I can integrate it in the CI.

**Comment by ojeda** [comment]
Thanks @nbdd0121! If you see any problems or you do not have time, let me know and I can do the CI missing bits.

**Comment by nbdd0121** [comment]
@ojeda I had a try, but I got a timeout and GitHub killed it without giving me much information. I don't have any machines with Ubuntu 20.04, and I tried to use nektos/act to test locally but it does not seem to support some constructs used in the CI script. I don't have much experience debugging GitHub actions; could you have a look if you have time? Thanks.

**Comment by ojeda** [comment]
Sure! Let me take a look.

**Comment by ojeda** [comment]
The bundled OpenSBI works fine for me in a VM, so no need to recompile.

The timing out issue is because 1) `CONFIG_SOC_VIRT` is not enabled and 2) `-no-reboot` does not seem to work for RISC-V in that version of QEMU. I compiled the latest QEMU and it works there.

The no output issue is due to something missing in the configuration, `defconfig` works.

I think the best approach is merging this without enabling `riscv` in the CI matrix just yet, and then I can look into adding a newer QEMU and enabling it.

**Comment by ojeda** [comment]
I will likely tweak a few minor nits later on, but I think we can merge this as-is.

Thanks a lot!

Referencing #66.

**Comment by alex** [comment]
We should add this to `arch-support.rst` as well!

**Comment by ojeda** [comment]
Yeah! I will do it when actually enabling it in the CI matrix.

**Pull request merged**
