### PR TITLE
seq_file.rs: Borrow data from C pointer

### PR DESCRIPTION
**Pull request by adamrk**
Borrow the `seq_file` data from the C pointer using `PointerWrapper::borrow` instead of taking ownership and then using `mem::forget`. This contains the changes of https://github.com/Rust-for-Linux/linux/pull/232.

Note: I've added `UnsafeReference` to the `kernel` module's public interface because the doctest example for `seq_file` wraps the data in a `Box`. This means the user is going to need to extract the data from `<Box as PointerWrapper>::Borrow` which is `UnsafeReference`. Was it intentional that for `UnsafeReference` to not be public?

### CODE REVIEW

**Comment by ksquirrel** [comment]
Review of `55813d497b79`:
  - ⚠️ This PR changes more than 20 files.
  - ⚠️ This PR adds/deletes more than 500 lines.
  - ✔️ Commit [`4f0aeff`](https://github.com/Rust-for-Linux/linux/commit/4f0aeff00e8eb03eb05455881a4b4066e6812b7d): Looks fine!
  - ✔️ Commit [`2fc05b5`](https://github.com/Rust-for-Linux/linux/commit/2fc05b510fdd0830ead04d3d882f6eee7df0e659): Looks fine!
  - ✔️ Commit [`55813d4`](https://github.com/Rust-for-Linux/linux/commit/55813d497b7952dbcbb450ee467c2a7ad6e44165): Looks fine!

**Comment by TheSven73** [comment]
Hi Adam, what is the goal here? Is this so Rust kernel components (drivers, fses, etc) can create `procfs` entries? I believe that `procfs` has been deprecated for quite some time, i.e. no new kernel components may add to `procfs` - but I could be wrong. Do you need this for anything specific?

**Comment by adamrk** [comment]
> Hi Adam, what is the goal here? Is this so Rust kernel components (drivers, fses, etc) can create `procfs` entries? I believe that `procfs` has been deprecated for quite some time, i.e. no new kernel components may add to `procfs` - but I could be wrong. Do you need this for anything specific?

Yes that's the goal. I don't need it for anything specific, more just trying out how wrapping some kernel APIs would work and figured someone might want it at some point. I was planning to add support for `debugfs` entries using `seq_file` as a follow up - do you think I should just get rid of the `procfs` stuff and only support `debugfs`?

**Comment by adamrk** [comment]
redoing this

**Pull request closed without merging**
