### PR TITLE
Add "semaphore" sample driver in C and Rust.

### PR DESCRIPTION
**Pull request by wedsonaf**

### CODE REVIEW

**Review by alex — COMMENTED** [review]
Can you add a comment to oen of these explaining what the behavior of the device is?

**Comment by ojeda** [comment]
Needs to be added to the CI -- but I can do it for you after merging (assuming you have at least ran it yourself! :-)

**Review by alex — APPROVED** [review]
With the comment to explain, everything became very clear :-)

**Comment by wedsonaf** [comment]
> Can you add a comment to oen of these explaining what the behavior of the device is?

Done. Please PTAL.

> Needs to be added to the CI -- but I can do it for you after merging (assuming you have at least ran it yourself! :-)

Yes, I ran both of them. :)

**Comment by ojeda** [comment]
I will clean up a couple things later today and add it to the CI.

**Pull request merged**
