### PR TITLE
Split Rust arguments into a new `scripts/Makefile.rust`

### PR DESCRIPTION
**Pull request by tgross35**
This follows the discussion at https://github.com/Rust-for-Linux/linux/pull/1025

### CODE REVIEW

**Comment by tgross35** [comment]
I'm not sure how much splitting you were interested in @ojeda. This patch as-is currently just moves the flags, but I also experimented with moving almost everything Rust-related to this file (KBUILD_x and all the Rust-related targets), which could be cleaner overall.

(side note - I wonder if it would be possible to have a `rustcheck` target like `cargo check` that verifies but doesn't build anything)

**Comment by ojeda** [comment]
I would only move the common flags to begin with and do so in the same patch series that adds the other lints/comments, because that is the motivation for this move, and keeps things simple. If we don't have a fair amount of comments/lints to add, it would be simpler to avoid the move altogether.

Unless we want to go for an actual refactor, that is. It is true that we could move other flags and other bits, and that was half my intention for using the name `scripts/Makefile.rust` (i.e. to allow for extra expansion/moves later). But then it falls more into Kbuild territory, and it would be done as a refactor rather than due to the lints.

**Comment by tgross35** [comment]
Understood, I was thinking that it would be preferred to keep this top-level change separate from the other Rust-specific changes - but I will merge them back together. Thanks for the look!

**Comment by ojeda** [comment]
My pleasure! Thanks for working on this and taking a look at the different potential approaches, it is appreciated!

**Pull request closed without merging**
