### PR TITLE
Docs: Add example to rust-analyzer setup.

### PR DESCRIPTION
**Pull request by Perpixel**
I feel this would be more obvious for the reader.

### CODE REVIEW

**Comment by ojeda** [comment]
Thanks for the PR! Development/changes should be submitted to the mailing list (please see https://rust-for-linux.com/contributing).

**Comment by ojeda** [comment]
https://lore.kernel.org/rust-for-linux/y4jBalhfESeCZDShmVaGwrdlIRoIHroqNVUUYLck6qGNwB5e7wbIJO5DoiLBTPpTNYtdneWRODjhXwlIl9VzokqxffdNU7y__1wIa7BBl94=@protonmail.com/

**Comment by ojeda** [comment]
Thanks for sending it, by the way!

**Comment by Perpixel** [comment]
No problem. I was tacking a chance with it seeing that we shouldn't send patchs with protonmail in the kernel docs.

**Pull request closed without merging**
