### PR TITLE
binder: Reject transactions containig FDs when they're not allowed.

### PR DESCRIPTION
**Pull request by wedsonaf**
Signed-off-by: Wedson Almeida Filho <wedsonaf@google.com>

### CODE REVIEW

**Comment by ksquirrel** [comment]
Review of `a4bc7459e947`:
  - ✔️ Commit [`a4bc745`](https://github.com/Rust-for-Linux/linux/commit/a4bc7459e94731e39c5d19dbb0a3747445f34e18): Looks fine!

**Comment by ojeda** [comment]
LGTM except the commit title :P

`containig` -> `containing`

**Comment by ksquirrel** [comment]
Review of `b42fcef8c37d`:
  - ✔️ Commit [`b42fcef`](https://github.com/Rust-for-Linux/linux/commit/b42fcef8c37d6198d08e6a717cb31fa8c4fb9b08): Looks fine!

**Comment by wedsonaf** [comment]
> LGTM except the commit title :P
> 
> `containig` -> `containing`

Fixed, thanks for spotting this! :)

**Pull request merged**
