### PR TITLE
Remove unnecessary param in Module::init

### PR DESCRIPTION
**Pull request by gipsyh**
we can get name from `ThisModule`, so `name` param is unnecessary.

### CODE REVIEW

**Comment by bjorn3** [comment]
cc https://github.com/Rust-for-Linux/linux/issues/720

@gipsyh Have you checked that https://github.com/Rust-for-Linux/linux/issues/720#issuecomment-1073035475 is not the case?

**Comment by gipsyh** [comment]
> cc #720
> 
> @gipsyh Have you checked that [#720 (comment)](https://github.com/Rust-for-Linux/linux/issues/720#issuecomment-1073035475) is not the case?

I checked, I think the `init` func in `Module` trait in rust is equal to `module_init(func)` in C, where func is `int (void)`, and there is no `name` param in `func`

**Comment by gipsyh** [comment]
> cc #720
> 
> @gipsyh Have you checked that [#720 (comment)](https://github.com/Rust-for-Linux/linux/issues/720#issuecomment-1073035475) is not the case?

I checked, I think the `init` func in `Module` trait in rust is equal to `module_init(func)` in C, where func is `int (void)`, and there is no `name` param in `func`

**Comment by gipsyh** [comment]
> cc #720
> 
> @gipsyh Have you checked that [#720 (comment)](https://github.com/Rust-for-Linux/linux/issues/720#issuecomment-1073035475) is not the case?

And in C, we uausally get name through `module_name(THIS_MODULE)`, which get name ptr from THIS_MODULE ptr.

So, In rust, we can also get name from ThisModule. It's redundant for `name param` in `Module::init`

**Pull request closed without merging**
