### PR TITLE
Update in quick-start.rst the symbol name CONFIG_RUST to RUST 

### PR DESCRIPTION
**Pull request by sergiocollado**
In the document quick-start.rst, in the Configuration section, is
refered the symbol `CONFIG_RUST` but this symbol, now is named `RUST`. 
This commit updates the name.

CONFIG_RUST_or_RUST

Signed-off-by: Sergio González Collado <sergio.collado@gmail.com>

### CODE REVIEW

**Review by bjorn3 — APPROVED** [review]

**Comment by ojeda** [comment]
I used `CONFIG_` here to clarify we are referring to the Kconfig symbol.

However, I am not sure I understand the following:

> but this symbol, now is named RUST.

What do you mean? The symbol hasn't changed, i.e. it is still `RUST` / `CONFIG_RUST`.

**Comment by sergiocollado** [comment]
Oh, was it always named `RUST`? My bad, I assumed it was named `CONFIG_RUST`, and somehow it was renamed to `RUST`. 

I would consider anyway use `RUST` in the document. I searched for the `CONFIG_RUST` symbol, and didn't find it, I assumed the symbol was the same, but had changed its name.

**Comment by sergiocollado** [comment]
@ojeda you are right the symbol is defined as `CONFIG_RUST`,  I was misleaded by the name that appeared at `menuconfig`.  I will close this PR.

**Comment by ojeda** [comment]
Yeah, it is a bit confusing :)

All symbols have the `CONFIG_` prefix (when seen from C or from the `.config` file), it is just that in Kconfig you don't spell it with it (e.g. `config RUST`). In `menuconfig` in particular, it is inconsistent: sometimes they show the prefix, and sometimes they do.

Hopefully that helps explain a bit!

**Pull request closed without merging**
