### PR TITLE
Implement `Display` and `Debug` for `CStr`

### LINKED ISSUE #534: Implement `Display` for `CStr` and `BStr`
In addition to https://github.com/Rust-for-Linux/linux/issues/532, it would be nice to implement `Display` for `CStr` and `BStr`.

Be careful to avoid panicking if invalid UTF-8 is found (i.e. do not attempt to convert it into a `&str`). We could escape all non-printable ASCII bytes to avoid losing data (e.g. `\x01`). Another way (but lossy) is using a replacement character (e.g. the Unicode one).

Unit-testing is a plus!

*[If there was a `Display`-like trait that would work for non-UTF-8, we could leave the escaping to `Debug` and just submit the bytes as-is for `Display` like `printk()` does for `%s`. But do we actually want this anyway? I don't know about a use case; in `printk` it is done like this because it is how `printf` works, I assume, and because we use macros to prefix the level etc.]*

### PR DESCRIPTION
**Pull request by mbartlett21**
This only prints ASCII characters and escapes the rest for `Display` and `Debug`.

(Fixes part of #534)

### CODE REVIEW

**Comment by ojeda** [comment]
Thanks a lot for contributing!

A few comments:
  - Please squash the commits and sign them (in the `Signed-off-by:` sense) to show you agree with the Developer's Certificate of Origin (see `Documentation/process/submitting-patches.rst`).
  - I love what you did here (it is a great example of how to use pattern matching), but I don't think we need to parse UTF-8 in the kernel (at least for the usual logging). Printing ASCII printable characters and escaping the rest should be enough. Note that eventually we might get to remove all Unicode-related facilities.
  - As it is right now, it prints characters such as 0 as-it-is, rather than escaping them.

**Comment by mbartlett21** [comment]
@ojeda 

I have squashed and signed the commits.

With the utf8 parsing, I think I might instead see if I can get it in the standard library (it already has utf16 parsing)

**Comment by ojeda** [comment]
> I have squashed and signed the commits.

Thanks! It looks good to me (both the code and the commit). Could you please add a doc with an example (which would double as test)?

> With the utf8 parsing, I think I might instead see if I can get it in the standard library (it already has utf16 parsing)

That would be great, yeah! Please let me know if you open the issue upstream, I would like to follow it.

**Comment by mbartlett21** [comment]
> That would be great, yeah! Please let me know if you open the issue upstream, I would like to follow it.

@ojeda 
It seems that Rust already had a way to decode utf8 to `char`s, but it was deprecated and removed in favour of utilising `core::str::from_utf8` and its error type.

Previous tracking issue: https://github.com/rust-lang/rust/issues/33906
Example use of `core::str::from_utf8`: https://doc.rust-lang.org/std/str/struct.Utf8Error.html#examples

**Comment by ojeda** [comment]
Thanks!

**Pull request merged**
