### PR TITLE
Extremely minor spelling fix

### PR DESCRIPTION
**Pull request by tgross35**
Saw this in the linux merge commit and couldn't unsee it

### CODE REVIEW

**Comment by tgross35** [comment]
(if anyone can cancel the workflow, that is probably a good idea. I was unable to find an option to skip)

**Comment by bjorn3** [comment]
Thanks for catching this! Before we can merge this, please see https://github.com/Rust-for-Linux/linux/pull/868#issuecomment-1255065713:

> Note that you will need to use your real name for submitting patches to the upstream kernel and sign off the commit (for the DCO). Please see https://docs.kernel.org/process/submitting-patches.html#sign-your-work-the-developer-s-certificate-of-origin

**Comment by tgross35** [comment]
This slipped my mind, but should be all set now

**Review by bjorn3 — APPROVED** [review]

**Comment by ojeda** [comment]
Thanks!

**Pull request merged**
