### PR TITLE
Add RUST_LIB_SRC make argument for nix builds

### PR DESCRIPTION
**Pull request by kloenk**
This can also used in an other non rustup context to improve usability.

CC: @ojeda

### CODE REVIEW

**Comment by ojeda** [comment]
I am not sure about the variable name, but if this fixes issues with Nix, let's put it in.

Just please note that if someone requests that we change the name before merging into mainline, it could change and I assume that would require a change in Nix files. i.e. let's not promise stability on that name just yet, if you agree.

**Comment by kloenk** [comment]
That's fine for me. Before this we patch the Makefile with sed. Not sure which is more stable :-). 

I also see pipeline fails? Maybe something with ?= ? I don't have a working setup with rustup at the moment. Maybe you could Test to make sure it works as expected with rustup?

**Comment by ojeda** [comment]
The latest force-push (on `3f46885`) seems to pass, do you mean the previous ones?

**Comment by kloenk** [comment]
Im not sure which reversion. If it works, I'm happy 😀

**Pull request merged**
