### PR TITLE
Fix build errors due to merge of previous PR

### PR DESCRIPTION
**Pull request by TheSven73**
#273 introduced a build issue in the `hwrng` Rust driver. Fixed. Added  that driver to the CI to prevent this from happening in the future.

### CODE REVIEW

**Comment by ksquirrel** [comment]
Review of `0b7dab045a54`:
  - ⚠️ This PR adds/deletes more than 500 lines.
  - ✔️ Commit [`9754b5f`](https://github.com/Rust-for-Linux/linux/commit/9754b5f80572b3a8f5b69daadcbfff19b64859c5): Looks fine!
  - ✔️ Commit [`563e630`](https://github.com/Rust-for-Linux/linux/commit/563e630fcb9fc0a24dd3d007f6b99cd255e9f0f7): Looks fine!
  - ✔️ Commit [`0b7dab0`](https://github.com/Rust-for-Linux/linux/commit/0b7dab045a54ad5c264b799dd9e5e3ad4108088c): Looks fine!

**Comment by ojeda** [comment]
Conflicts -- otherwise LGTM!

**Comment by ksquirrel** [comment]
Review of `07de3a4ec0bd`:
  - ⚠️ This PR adds/deletes more than 500 lines.
  - ✔️ Commit [`75a270d`](https://github.com/Rust-for-Linux/linux/commit/75a270d25f476556cbc1b064f89bf5e5a4d85197): Looks fine!
  - ✔️ Commit [`03e769a`](https://github.com/Rust-for-Linux/linux/commit/03e769a7ba870f1d1f603cb79bc78e20a14e2197): Looks fine!
  - ✔️ Commit [`07de3a4`](https://github.com/Rust-for-Linux/linux/commit/07de3a4ec0bdac3fc683c05fc2b66d3492dce7a7): Looks fine!

**Comment by TheSven73** [comment]
### v1 -> v2
Rebased to avoid merge conflict.

**Comment by ojeda** [comment]
Hmm... the first commit removes most of the config.

**Comment by TheSven73** [comment]
> Hmm... the first commit removes most of the config.

I believe it's correct. There are two ways to create a `defconfig`:
1. simply copy `.config`
2. run `make savedefconfig` which generates a file called `defconfig`

Method (1) creates a `defconfig` that explicitly contains every setting. Method (2) leaves out those settings that are equal to their default (indicated in `Kconfig`).

What happened here, is that a verbose `defconfig` was replaced by a short `defconfig`.

Should this be split into an extra commit? Or keep verbose `defconfig` ? The latter makes diffing much harder.

**Comment by ojeda** [comment]
If we are going for the short configs, we should do that in another PR, updating all the arches at once.

So for the moment, please keep the long ones to be consistent.

**Comment by TheSven73** [comment]
Sure, but it will get messy. Adding support for the BCM2835 chip will probably add a lot of extra `defconfig` items. They're all equal to their defaults, but will nevertheless show up in the diff.

**Comment by ksquirrel** [comment]
Review of `d6566105835d`:
  - ✔️ Commit [`4266a32`](https://github.com/Rust-for-Linux/linux/commit/4266a32857591f0f55583fc4504b387e6c7a9597): Looks fine!
  - ✔️ Commit [`6d7443c`](https://github.com/Rust-for-Linux/linux/commit/6d7443cdf9b4d695b44ea35ba22d52a2fc7bedf8): Looks fine!
  - ✔️ Commit [`d656610`](https://github.com/Rust-for-Linux/linux/commit/d6566105835d1c37f696d8dcd7913274311904f3): Looks fine!

**Comment by TheSven73** [comment]
### v2 -> v3
ojeda: Commit `defconfig`s using the verbose method.

**Comment by ojeda** [comment]
It doesn't look that bad! Thanks!

By the way, it does not really matter for us, but normally I would put the fix first, and then enable it in the CI second (otherwise, if we had a CI that compiled all commits -- like we may in the future, it would be an error).

**Comment by TheSven73** [comment]
Yes, very good point, I'll make sure that happens in the future. Thanks for the merge ! :100:

**Pull request merged**
