### PR TITLE
Preparation for linux-next

### PR DESCRIPTION
**Pull request by ojeda**

### CODE REVIEW

**Comment by alex** [comment]
Can you explain what this does a bit more verbosely? If Rust is going to be conditional on this parameter, we need to update the configs we use in test, right?

**Comment by ojeda** [comment]
> Can you explain what this does a bit more verbosely?

Of course, sorry: this is intended to avoid breaking others' allmodconfig etc. builds when joining linux-next if they have `rustc` installed.

I was weighing different solutions (like modifying the config generators to skip the option, or removing GCC builds for the moment + adding more checks to reduce the set of people for which the Kconfig option appears), but when discussing it with Stephen he helpfully suggested using `!COMPILE_TEST`, which is the easiest (and other bits of the kernel already use for similar purposes).

> If Rust is going to be conditional on this parameter, we need to update the configs we use in test, right?

The configs already had `COMPILE_TEST` disabled, as it is usually the case (e.g. other configs like the kernel's `defconfig` have it disabled, too).

**Comment by alex** [comment]
Hmm, so a while ago Linus opined that we should enable this stuff by default whenever rustc was installed (I can dig up the mailing list post of it'd be helpful), do you think that's no longer true?

**Comment by ojeda** [comment]
Yeah, Linus said he didn't want things build-tested by default under allmodconfig etc., which is very reasonable, and this deviates from that. However, currently knowing whether the environment is correct or not is more complex than a version check, e.g. bindgen may be missing, or the Rust source code, etc.

So one alternative is adding all those checks as I mentioned, but it has downsides: mainly adding too much magic to the configuration, but also things like normal users being confused as to why the option does not appear. In general, I think options that disappear based on complex conditions are hard to understand. [+]

Thus the idea here is to, for the moment, skip it in order to join linux-next minimizing any breakage to others and go into the RFC. During the RFC, or later, we can all discuss better how we will handle this:
  - Ideally, Linus would just say "OK, let's do this", at which point it is easier to have everyone running CIs and allmodconfig to have the right environment, so that we can remove `!COMPILE_TEST` (without adding the magic checks; and taking care of what to do with GCC builds, etc.).
  - Or, perhaps, we do it in steps: e.g. Stephen told me he will likely install Rust if the ball starts rolling, so perhaps he can have initially a special run just for the Rust branch where he enables it on top of allmodconfig, so that it is guaranteed to be build-tested by, at least, him.
  - Similarly, we could have increased coverage in the CI, e.g. some sponsor could give us a 32-core VM somewhere to run an allmodconfig x86_64 kernel build on every PR, etc.

In general, my feeling is that Linus was more concerned about people creating their own broken mini-world within the kernel than with the actual solution we find to achieve things. But we are definitely not trying to have our own broken mini-world, so we need to make it very clear! :-)

---

[+] In fact, I'd try to convince Linus that we should not test at all if `rustc` is available -- let users choose the option or not, and let it fail if they don't have the right setup. The reason is that things like `ld` being `lld` that he mentioned seem different: typically you had to explicitly pass `LLVM=1` or similar; plus Rust support looks, at the moment, more like a "feature" of the kernel, rather than an "option" like Clang vs. GCC or a hard requirement like a dependency on a particular arch (which there is nothing one can do to "fix"). But this is orthogonal to the issue.

**Review by alex — APPROVED** [review]

**Pull request merged**
