### PR TITLE
rust: implement static_assert! in a more idiomatic way

### PR DESCRIPTION
**Pull request by alex**
Signed-off-by: Alex Gaynor <alex.gaynor@gmail.com>

### CODE REVIEW

**Comment by alex** [comment]
Hmmm, the doctest code relies on overriding `assert!` with an assertion that's not usable in `const` contexts.

I don't see an obvious way to work around this, but it also seems unfortunate to be stuck with this kludgy implementation of `static_assert!` for forever.

**Review by bjorn3 — APPROVED** [review]
Now that assert!() is supported in const contexts that is definitively much clearer!

**Comment by bjorn3** [comment]
> Hmmm, the doctest code relies on overriding assert! with an assertion that's not usable in const contexts.

You could refer to `core::panic!()` rather than `panic!()` I think.

**Comment by nbdd0121** [comment]
`core::assert!` will generate fully qualified use of `panic!`, so `core::assert!` should be sufficient.

**Review by bjorn3 — APPROVED** [review]

**Comment by ojeda** [comment]
Much better, thanks all!

**Comment by nbdd0121** [comment]
The commits are not signed off.

**Pull request merged**
