### PR TITLE
Bump `bindgen`'s version and use new features

### PR DESCRIPTION
**Pull request by pvdrz**

### CODE REVIEW

**Comment by ojeda** [comment]
Few comments on this:

  - This requires the new `bindgen` in the container image used by the CI (I can provide that, but currently the CI will not pass).

  - Did you check the generated bindings and compared them with the current version? Are there any significant changes? Providing the diff would be useful (before using any new features).

  - The commit mixes several changes and there is no commit message at all. The DCO signature is missing too. Please read https://www.kernel.org/doc/html/latest/process/submitting-patches.html -- the kernel has a few requirements to accept patches.

  - Please do a commit bumping the version first, then one per new feature being used, explaining briefly what is the feature about and why we want to apply it. Each commit could contain an example diff of how the generated bindings will change.

Thanks a lot for this!

**Comment by pvdrz** [comment]
Hi Miguel,

I tried as best to address your comments

> Did you check the generated bindings and compared them with the current version? Are there any significant changes? Providing the diff would be useful (before using any new features).

I added a small example to the changes to each one of the commit messages as adding a full diff seemed a bit too much imho.


> The commit mixes several changes and there is no commit message at all. The DCO signature is missing too. Please read https://www.kernel.org/doc/html/latest/process/submitting-patches.html -- the kernel has a few requirements to accept patches.

I added a brief description to each commit and added the sign-off. I hope this is enough.

> Please do a commit bumping the version first, then one per new feature being used, explaining briefly what is the feature about and why we want to apply it. Each commit could contain an example diff of how the generated bindings will change.

I divided the commit into several smaller commits that compile on their own.

**Comment by nbdd0121** [comment]
The changes LGTM.

Please include the subsystem touched in the commit subject: e.g. "Update `bindgen` to version 0.63.0" -> "rust: update `bindgen` to version 0.63.0"

**Comment by ojeda** [comment]
The split looks great! Thanks.

For things like "This flag is no longer required as recent versions of `bindgen`", could you please mention the version? You may also link to the changelog/issur/PR to give the full context (and since you were the one working on these improvements on `bindgen`, even better :) For instance, you could write something like:

```text
The `--ctypes-prefix core::ffi`  flag is no longer needed since, starting with
bindgen 0.61.0 [1,2,3], the `::core::ffi` path prefix will be automatically used
when the `--use-core` flag is enabled and Rust >= 1.64 is used.

Link: https://github.com/rust-lang/rust-bindgen/blob/v0.61.0/CHANGELOG.md#0610 [1]
Link: https://github.com/rust-lang/rust-bindgen/issues/2231 [2]
Link: https://github.com/rust-lang/rust-bindgen/pull/2267 [3]
Signed-off-by: ...
```

(I used the tag for the changelog vs. `master` to make the URL a bit more permanent.)

Which, by the way, I just noticed that Rust 1.64 since I was checking the changelog -- we are not using Rust 1.64 yet, so we may not be able to use the flag just yet even updating bindgen, right? Please check if it works on your side with the minimum Rust version, 1.62.0. (We could also wait until we update the minimum version, which we will want probably soon, ~a few weeks).

**Comment by pvdrz** [comment]
@ojeda 

> we are not using Rust 1.64 yet, so we may not be able to use the flag just yet even updating bindgen, right? Please check if it works on your side with the minimum Rust version, 1.62.0. 

Oh that's right... sorry :sweat_smile:. I'm going to drop that commit and this should be ready. There are more changes I'd like to do in the future so there's no rush about merging that particular commit from my side.

**Comment by yu-re-ka** [comment]
I am running into a `error: Found argument '--blacklist-type' which wasn't expected, or isn't valid in this context. Did you mean '--blocklist-type'?` with bindgen 0.63.0. Can you have another look at this?

**Comment by pvdrz** [comment]
https://github.com/rust-lang/rust-bindgen/blob/master/CHANGELOG.md#removed-1

**Pull request closed without merging**
