### PR TITLE
Upgrade to Rust 1.56

### PR DESCRIPTION
**Pull request by ojeda**
Includes upgrade to `alloc` 1.56, removal of `const_fn_transmute`, docs and CI.

### CODE REVIEW

**Comment by nbdd0121** [comment]
I am working on it as well; it guess I'll just compare with my local version

**Comment by nbdd0121** [comment]
```diff
diff --git a/Makefile b/Makefile
index 1b9b6714b199..66e08593982a 100644
--- a/Makefile
+++ b/Makefile
@@ -531,7 +531,7 @@ KBUILD_CFLAGS   := -Wall -Wundef -Werror=strict-prototypes -Wno-trigraphs \
                   -std=gnu89
 KBUILD_CPPFLAGS := -D__KERNEL__
 KBUILD_RUST_TARGET := $(srctree)/arch/$(SRCARCH)/rust/target.json
-KBUILD_RUSTFLAGS := --emit=dep-info,obj,metadata --edition=2018 \
+KBUILD_RUSTFLAGS := --emit=dep-info,obj,metadata --edition=2021 \
                     -Cpanic=abort -Cembed-bitcode=n -Clto=n -Crpath=n \
                     -Cforce-unwind-tables=n -Ccodegen-units=1 \
                     -Zbinary_dep_depinfo=y -Zsymbol-mangling-version=v0 \
diff --git a/rust/alloc/lib.rs b/rust/alloc/lib.rs
index 6cf622ba39e0..1f96d0b98fad 100644
--- a/rust/alloc/lib.rs
+++ b/rust/alloc/lib.rs
@@ -87,7 +87,6 @@
 #![feature(allow_internal_unstable)]
 #![feature(arbitrary_self_types)]
 #![feature(async_stream)]
-#![cfg_attr(bootstrap, feature(bindings_after_at))]
 #![feature(box_patterns)]
 #![feature(box_syntax)]
 #![feature(cfg_sanitize)]
@@ -145,8 +144,7 @@
 #![feature(alloc_layout_extra)]
 #![feature(trusted_random_access)]
 #![feature(try_trait_v2)]
-#![cfg_attr(bootstrap, feature(min_type_alias_impl_trait))]
-#![cfg_attr(not(bootstrap), feature(type_alias_impl_trait))]
+#![feature(type_alias_impl_trait)]
 #![feature(associated_type_bounds)]
 #![feature(slice_group_by)]
 #![feature(decl_macro)]
diff --git a/rust/alloc/raw_vec.rs b/rust/alloc/raw_vec.rs
index 2dd2b6250047..ba9c0ac4c009 100644
--- a/rust/alloc/raw_vec.rs
+++ b/rust/alloc/raw_vec.rs
@@ -15,16 +15,16 @@ use core::slice;
 use crate::alloc::handle_alloc_error;
 use crate::alloc::{Allocator, Global, Layout};
 use crate::boxed::Box;
-use crate::collections::{TryReserveError, TryReserveErrorKind};
+use crate::collections::TryReserveError;
 use crate::collections::TryReserveErrorKind::*;
 
 #[cfg(test)]
 mod tests;
 
+#[allow(dead_code)]
 enum AllocInit {
     /// The contents of the new memory are uninitialized.
     Uninitialized,
-    #[allow(dead_code)]
     /// The new memory is guaranteed to be zeroed.
     Zeroed,
 }
@@ -241,19 +241,13 @@ impl<T, A: Allocator> RawVec<T, A> {
             return Ok(Self::new_in(alloc));
         }
 
-        let layout = match Layout::array::<T>(capacity) {
-            Ok(layout) => layout,
-            Err(layout_error) => return Err(TryReserveError::from(TryReserveErrorKind::from(layout_error))),
-        };
+        let layout = Layout::array::<T>(capacity).map_err(|_| CapacityOverflow)?;
         alloc_guard(layout.size())?;
         let result = match init {
             AllocInit::Uninitialized => alloc.allocate(layout),
             AllocInit::Zeroed => alloc.allocate_zeroed(layout),
         };
-        let ptr = match result {
-            Ok(ptr) => ptr,
-            Err(_) => return Err(TryReserveError::from(AllocError { layout, non_exhaustive: () })),
-        };
+        let ptr = result.map_err(|_| AllocError { layout, non_exhaustive: () })?;
 
         Ok(Self {
             ptr: unsafe { Unique::new_unchecked(ptr.cast().as_ptr()) },
diff --git a/rust/alloc/vec/mod.rs b/rust/alloc/vec/mod.rs
index 2621d568a79b..6576a058af34 100644
--- a/rust/alloc/vec/mod.rs
+++ b/rust/alloc/vec/mod.rs
@@ -74,7 +74,7 @@ use core::slice::{self, SliceIndex};
 use crate::alloc::{Allocator, Global};
 use crate::borrow::{Cow, ToOwned};
 use crate::boxed::Box;
-use crate::collections::{TryReserveError, TryReserveErrorKind};
+use crate::collections::TryReserveError;
 use crate::raw_vec::RawVec;
 
 #[unstable(feature = "drain_filter", reason = "recently added", issue = "43244")]
diff --git a/rust/alloc/vec/spec_extend.rs b/rust/alloc/vec/spec_extend.rs
index aeebb04b73d9..01a9ca0d261c 100644
--- a/rust/alloc/vec/spec_extend.rs
+++ b/rust/alloc/vec/spec_extend.rs
@@ -1,7 +1,7 @@
 // SPDX-License-Identifier: Apache-2.0 OR MIT
 
 use crate::alloc::Allocator;
-use crate::vec::{TryReserveError, TryReserveErrorKind};
+use crate::collections::{TryReserveError, TryReserveErrorKind};
 use core::iter::TrustedLen;
 use core::ptr::{self};
 use core::slice::{self};
```

**Comment by ojeda** [comment]
> I am working on it as well; it guess I'll just compare with my local version

Please do! I had to touch a few things for `alloc` etc., so a second pair of eyes is always good.

**Comment by ojeda** [comment]
```
> -KBUILD_RUSTFLAGS := --emit=dep-info,obj,metadata --edition=2018 \
> +KBUILD_RUSTFLAGS := --emit=dep-info,obj,metadata --edition=2021 \
```

I was planning to do this in another PR afterwards.

By the way, do we know if we hit any of the edge cases in the edition migration?

```
> -#![cfg_attr(bootstrap, feature(bindings_after_at))]
>  #![feature(try_trait_v2)]
> -#![cfg_attr(bootstrap, feature(min_type_alias_impl_trait))]
> -#![cfg_attr(not(bootstrap), feature(type_alias_impl_trait))]
> +#![feature(type_alias_impl_trait)]
```

Yeah, we don't need these, but it is best to be closer to upstream.

```
> +#[allow(dead_code)]
>  enum AllocInit {
>      /// The contents of the new memory are uninitialized.
>      Uninitialized,
> -    #[allow(dead_code)]
>      /// The new memory is guaranteed to be zeroed.
>      Zeroed,
>  }
```

I took the chance to move it since we had a modification anyway.

```
> -        let layout = match Layout::array::<T>(capacity) {
> -            Ok(layout) => layout,
> -            Err(layout_error) => return Err(TryReserveError::from(TryReserveErrorKind::from(layout_error))),
> -        };
> +        let layout = Layout::array::<T>(capacity).map_err(|_| CapacityOverflow)?;
```

Yeah, I could have simplified -- `LayoutError`s are converted to `CapacityOverflow` anyway. Let me change it to yours.

```
> -        let ptr = match result {
> -            Ok(ptr) => ptr,
> -            Err(_) => return Err(TryReserveError::from(AllocError { layout, non_exhaustive: () })),
> -        };
> +        let ptr = result.map_err(|_| AllocError { layout, non_exhaustive: () })?;
```

Ditto.

**Comment by nbdd0121** [comment]
So, the differences:
* I changed the edition to 2021
* I removed `cfg(bootstrap)`. My reasoning is that keeping it will make it closer to the 1.56 std, removing it will make closer to 1.57 std, which is closer to the upstream nightly std. And we don't (and can't) use our copy of alloc to bootstrap rustc.
* Some style differences (e.g. match vs ?).

> ```diff
> -        let layout = match Layout::array::<T>(capacity) {
> -            Ok(layout) => layout,
> -            Err(layout_error) => return Err(TryReserveError::from(TryReserveErrorKind::from(layout_error))),
> -        };
> +        let layout = Layout::array::<T>(capacity).map_err(|_| CapacityOverflow)?;
> ```
`TryReserveErrorKind::from(LayoutError)` will always give you `CapacityOverflow`.

>```diff
> -use crate::vec::{TryReserveError, TryReserveErrorKind};
> +use crate::collections::{TryReserveError, TryReserveErrorKind};
> ```

These are exported from `crate::collections`. You are using the "use" within `crate::vec` (which explains why I can remove an import).

**Comment by nbdd0121** [comment]
> By the way, do we know if we hit any of the edge cases in the edition migration?

I enabled the migration lints, and nothing fires.

**Comment by ojeda** [comment]
> * I removed `cfg(bootstrap)`. My reasoning is that keeping it will make it closer to the 1.56 std, removing it will make closer to 1.57 std, which is closer to the upstream nightly std. And we don't (and can't) use our copy of alloc to bootstrap rustc.

Yeah, it does not matter much. So far we have upgraded stable-step-by-stable-step, so let's keep doing the same. That way is easier to track and know what to compare against etc.

> These are exported from `crate::collections`. You are using the "use" within `crate::vec` (which explains why I can remove an import).

I followed the style nearby -- not sure why they are doing it, though...

(Actually, I don't know either why `TryReserve` etc. is in `collections`... :)

**Comment by nbdd0121** [comment]
> I followed the style nearby -- not sure why they are doing it, though...

There isn't anything nearby... This line is previously added by us as well.

**Comment by ojeda** [comment]
> There isn't anything nearby... This line is previously added by us as well.

Right you are! Then let's fix it, yeah.

**Review by nbdd0121 — APPROVED** [review]

**Comment by ojeda** [comment]
Thanks a lot for the double-do Gary! I know it can be frustrating to find out someone else was doing the same...

**Pull request merged**
