### PR TITLE
docs: Fix a typo in intra-doc link

### PR DESCRIPTION
**Pull request by rick68**
remove the extra left quotation mark

Signed-off-by: Hsiang-Cheng Yang <rick68@gmail.com>

### CODE REVIEW

**Review by alex — APPROVED** [review]

**Comment by ojeda** [comment]
@rick68 Commits for upstream Linux need to be signed, i.e. have a line like:

    Signed-off-by: Hsiang-Cheng Yang <your@email.com>

which certifies you have the right to submit the patch for inclusion into the kernel. It is an agreement to the DCO (please read `Documentation/process/`, in particular https://www.kernel.org/doc/html/latest/process/submitting-patches.html#developer-s-certificate-of-origin-1-1).

Could you please sign it here? Thanks!

**Comment by rick68** [comment]
@ojeda Thanks for your kindly reminder.

**Comment by ojeda** [comment]
@rick68 Sorry if it was not clear: could you please sign it by writing the `Signed-off-by` line here? (I know it may sound stupid for a trivial change, but we are required to do so)

**Comment by ojeda** [comment]
Ah, never mind, you edited the first message -- thanks a lot!

**Comment by alex** [comment]
@ojeda can we add a check to CI so we (well, _I_) don't forget to look for it?

**Comment by ojeda** [comment]
@alex Yeah, will do (it was one of the jobs of the @ksquirrel bot).

**Comment by rick68** [comment]
@ojeda Anyway, thanks again for your reminder. 😊

**Pull request merged**
